// Auto-generated by scripts/ingest_standards.py — do not edit.
// Isaac Raz MasterClass standards: 19 jazz tunes as playable HarmonicPaths.

import type { HarmonicPath } from "./paths";

export const STUDIES_PATHS: HarmonicPath[] = [
  {
    id: "study-star-eyes",
    title: "Star Eyes — Gene de Paul",
    description: "F · 130 BPM · Swing Medium · 32 bars",
    feel: "Swing Medium",
    composer: "Gene de Paul",
    key: "F",
    steps: [
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b1: Fmaj7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b2: Gm7 C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b3: Fmaj7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b4: Gm7 C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b5: Fmaj7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b6: Bbm7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b7: Am7 D7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b8: Gm7 C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b9: Fmaj7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b10: Gm7 C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b11: Fmaj7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b12: Gm7 C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b13: Fmaj7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b14: Bbm7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b15: Am7 D7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b16: Gm7 C7",
      },
      {
        name: "Fm7",
        notes: [65, 68, 72, 75],
        descriptions: "b17: Fm7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b18: Bbm7",
      },
      {
        name: "Eb7",
        notes: [63, 67, 70, 73],
        descriptions: "b19: Eb7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b20: Am7 D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b21: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b22: C7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b23: F7",
      },
      {
        name: "D7 Gm7 C7",
        notes: [62, 66, 69, 72],
        descriptions: "b24: D7 Gm7 C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b25: Fmaj7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b26: Gm7 C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b27: Fmaj7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b28: Gm7 C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b29: Fmaj7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b30: Bbm7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b31: Am7 D7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b32: Gm7 C7",
      },
    ],
  },
  {
    id: "study-is-you-is-or-is-you-aint-my-baby",
    title: "Is You Is or Is You Ain't My Baby — Billy Austin",
    description: "F · 130 BPM · Swing Medium · 32 bars",
    feel: "Swing Medium",
    composer: "Billy Austin",
    key: "F",
    steps: [
      {
        name: "F6",
        notes: [65, 69, 72],
        descriptions: "b1: F6",
      },
      {
        name: "F6",
        notes: [65, 69, 72],
        descriptions: "b2: F6",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b3: Bbm7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b4: Bbm7",
      },
      {
        name: "F6",
        notes: [65, 69, 72],
        descriptions: "b5: F6",
      },
      {
        name: "F6",
        notes: [65, 69, 72],
        descriptions: "b6: F6",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b7: Bbm7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b8: Bbm7",
      },
      {
        name: "F6",
        notes: [65, 69, 72],
        descriptions: "b9: F6",
      },
      {
        name: "F6",
        notes: [65, 69, 72],
        descriptions: "b10: F6",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b11: Bbm7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b12: Bbm7",
      },
      {
        name: "F6",
        notes: [65, 69, 72],
        descriptions: "b13: F6",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b14: D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b15: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b16: C7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b17: D7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b18: D7",
      },
      {
        name: "G7",
        notes: [67, 71, 74, 77],
        descriptions: "b19: G7",
      },
      {
        name: "G7",
        notes: [67, 71, 74, 77],
        descriptions: "b20: G7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b21: C7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b22: C7",
      },
      {
        name: "F6",
        notes: [65, 69, 72],
        descriptions: "b23: F6",
      },
      {
        name: "D7 Gm7 C7",
        notes: [62, 66, 69, 72],
        descriptions: "b24: D7 Gm7 C7",
      },
      {
        name: "F6",
        notes: [65, 69, 72],
        descriptions: "b25: F6",
      },
      {
        name: "F6",
        notes: [65, 69, 72],
        descriptions: "b26: F6",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b27: Bbm7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b28: Bbm7",
      },
      {
        name: "F6",
        notes: [65, 69, 72],
        descriptions: "b29: F6",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b30: D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b31: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b32: C7",
      },
    ],
  },
  {
    id: "study-yardbird-suite",
    title: "Yardbird Suite — Charlie Parker",
    description: "F · 220 BPM · Swing Up · 32 bars",
    feel: "Swing Up",
    composer: "Charlie Parker",
    key: "F",
    steps: [
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b1: F7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b2: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b3: F7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b4: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b5: F7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b6: D7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b7: Gm7 C7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b8: F7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b9: F7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b10: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b11: F7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b12: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b13: F7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b14: D7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b15: Gm7 C7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b16: F7",
      },
      {
        name: "Bb",
        notes: [70, 74, 77],
        descriptions: "b17: Bb",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b18: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b19: F7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b20: D7",
      },
      {
        name: "G7",
        notes: [67, 71, 74, 77],
        descriptions: "b21: G7",
      },
      {
        name: "G7",
        notes: [67, 71, 74, 77],
        descriptions: "b22: G7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b23: C7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b24: C7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b25: F7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b26: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b27: F7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b28: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b29: F7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b30: D7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b31: Gm7 C7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b32: F7",
      },
    ],
  },
  {
    id: "study-sometimes-im-happy",
    title: "Sometimes I'm Happy — Vincent Youmans",
    description: "Bb · 120 BPM · Swing Medium · 32 bars",
    feel: "Swing Medium",
    composer: "Vincent Youmans",
    key: "Bb",
    steps: [
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b1: Bb6",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b2: Bb6",
      },
      {
        name: "Bbm7 Eb7",
        notes: [70, 73, 77, 80],
        descriptions: "b3: Bbm7 Eb7",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b4: Bb6",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b5: Bb6",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b6: Bb6",
      },
      {
        name: "Bbm7 Eb7",
        notes: [70, 73, 77, 80],
        descriptions: "b7: Bbm7 Eb7",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b8: Bb6",
      },
      {
        name: "Bb6 Gm7",
        notes: [70, 74, 77],
        descriptions: "b9: Bb6 Gm7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b10: Cm7 F7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b11: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b12: Ebmaj7",
      },
      {
        name: "Bb6 Gm7",
        notes: [70, 74, 77],
        descriptions: "b13: Bb6 Gm7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b14: Cm7 F7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b15: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b16: Ebmaj7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b17: Am7 D7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b18: Gm7 C7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b19: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b20: Ebmaj7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b21: Am7 D7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b22: Gm7 C7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b23: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b24: Ebmaj7",
      },
      {
        name: "Bb6 Gm7",
        notes: [70, 74, 77],
        descriptions: "b25: Bb6 Gm7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b26: Cm7 F7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b27: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b28: Ebmaj7",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b29: Bb6",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b30: Bb6",
      },
      {
        name: "Bbm7 Eb7",
        notes: [70, 73, 77, 80],
        descriptions: "b31: Bbm7 Eb7",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b32: Bb6",
      },
    ],
  },
  {
    id: "study-solar",
    title: "Solar — Miles Davis",
    description: "G- · 140 BPM · Swing Medium · 32 bars",
    feel: "Swing Medium",
    composer: "Miles Davis",
    key: "G-",
    steps: [
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b1: Gm7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b2: Cm7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b3: Gm7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b4: Cm7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b5: Gm7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b6: Cm7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b7: Gm7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b8: Cm7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b9: Gm7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b10: Cm7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b11: Gm7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b12: Cm7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b13: Gm7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b14: Cm7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b15: Gm7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b16: Cm7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b17: Cm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b18: F7",
      },
      {
        name: "Bbmaj7",
        notes: [70, 73, 77, 81],
        descriptions: "b19: Bbmaj7",
      },
      {
        name: "Bbmaj7",
        notes: [70, 73, 77, 81],
        descriptions: "b20: Bbmaj7",
      },
      {
        name: "Am7b5 D7",
        notes: [69, 72, 75, 79],
        descriptions: "b21: Am7b5 D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b22: Gm7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b23: Gm7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b24: Gm7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b25: Gm7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b26: Cm7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b27: Gm7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b28: Cm7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b29: Gm7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b30: Cm7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b31: Gm7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b32: Cm7",
      },
    ],
  },
  {
    id: "study-what-is-this-thing-called-love",
    title: "What Is This Thing Called Love — Cole Porter",
    description: "Ab · 140 BPM · Swing Medium · 32 bars",
    feel: "Swing Medium",
    composer: "Cole Porter",
    key: "Ab",
    steps: [
      {
        name: "Abmaj7",
        notes: [68, 71, 75, 79],
        descriptions: "b1: Abmaj7",
      },
      {
        name: "G7",
        notes: [67, 71, 74, 77],
        descriptions: "b2: G7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b3: Cm7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b4: Cm7 F7",
      },
      {
        name: "Fm7",
        notes: [65, 68, 72, 75],
        descriptions: "b5: Fm7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b6: Bbm7",
      },
      {
        name: "Eb7",
        notes: [63, 67, 70, 73],
        descriptions: "b7: Eb7",
      },
      {
        name: "Dbmaj7",
        notes: [61, 64, 68, 72],
        descriptions: "b8: Dbmaj7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b9: Cm7 F7",
      },
      {
        name: "Fm7 Bbm7",
        notes: [65, 68, 72, 75],
        descriptions: "b10: Fm7 Bbm7",
      },
      {
        name: "Eb7",
        notes: [63, 67, 70, 73],
        descriptions: "b11: Eb7",
      },
      {
        name: "Dbmaj7",
        notes: [61, 64, 68, 72],
        descriptions: "b12: Dbmaj7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b13: Cm7 F7",
      },
      {
        name: "Fm7 Bbm7",
        notes: [65, 68, 72, 75],
        descriptions: "b14: Fm7 Bbm7",
      },
      {
        name: "Eb7",
        notes: [63, 67, 70, 73],
        descriptions: "b15: Eb7",
      },
      {
        name: "Dbmaj7",
        notes: [61, 64, 68, 72],
        descriptions: "b16: Dbmaj7",
      },
      {
        name: "Dbmaj7",
        notes: [61, 64, 68, 72],
        descriptions: "b17: Dbmaj7",
      },
      {
        name: "Bbm7 Eb7",
        notes: [70, 73, 77, 80],
        descriptions: "b18: Bbm7 Eb7",
      },
      {
        name: "Abmaj7",
        notes: [68, 71, 75, 79],
        descriptions: "b19: Abmaj7",
      },
      {
        name: "G7",
        notes: [67, 71, 74, 77],
        descriptions: "b20: G7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b21: Cm7",
      },
      {
        name: "Fm7",
        notes: [65, 68, 72, 75],
        descriptions: "b22: Fm7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b23: Bbm7",
      },
      {
        name: "Eb7",
        notes: [63, 67, 70, 73],
        descriptions: "b24: Eb7",
      },
      {
        name: "Abmaj7",
        notes: [68, 71, 75, 79],
        descriptions: "b25: Abmaj7",
      },
      {
        name: "G7",
        notes: [67, 71, 74, 77],
        descriptions: "b26: G7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b27: Cm7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b28: Cm7 F7",
      },
      {
        name: "Fm7",
        notes: [65, 68, 72, 75],
        descriptions: "b29: Fm7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b30: Bbm7",
      },
      {
        name: "Eb7",
        notes: [63, 67, 70, 73],
        descriptions: "b31: Eb7",
      },
      {
        name: "Dbmaj7",
        notes: [61, 64, 68, 72],
        descriptions: "b32: Dbmaj7",
      },
    ],
  },
  {
    id: "study-lady-be-good",
    title: "Lady Be Good — George Gershwin",
    description: "G · 180 BPM · Swing Up · 36 bars",
    feel: "Swing Up",
    composer: "George Gershwin",
    key: "F",
    steps: [
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b1: Gmaj7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b2: Gmaj7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b3: Gmaj7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b4: Gmaj7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b5: Gmaj7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b6: Am7 D7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b7: Gmaj7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b8: Am7 D7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b9: Gmaj7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b10: Gmaj7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b11: Gmaj7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b12: Gmaj7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b13: Gmaj7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b14: Am7 D7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b15: Gmaj7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b16: Am7 D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b17: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b18: C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b19: Fmaj7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b20: Fmaj7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b21: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b22: C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b23: Fmaj7",
      },
      {
        name: "F#o7",
        notes: [66, 69, 72, 75],
        descriptions: "b24: F#o7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b25: Gmaj7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b26: Gmaj7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b27: Gmaj7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b28: Gmaj7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b29: Gmaj7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b30: Am7 D7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b31: Gmaj7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b32: Am7 D7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b33: Gmaj7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b34: Gmaj7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b35: Gmaj7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b36: D7",
      },
    ],
  },
  {
    id: "study-cherokee",
    title: "Cherokee — Ray Noble",
    description: "Bb · 200 BPM · Swing Up · 32 bars",
    feel: "Swing Up",
    composer: "Ray Noble",
    key: "Bb",
    steps: [
      {
        name: "Bb",
        notes: [70, 74, 77],
        descriptions: "b1: Bb",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b2: Cm7 F7",
      },
      {
        name: "Bb",
        notes: [70, 74, 77],
        descriptions: "b3: Bb",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b4: Cm7 F7",
      },
      {
        name: "Bb",
        notes: [70, 74, 77],
        descriptions: "b5: Bb",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b6: Cm7 F7",
      },
      {
        name: "Bb",
        notes: [70, 74, 77],
        descriptions: "b7: Bb",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b8: Cm7 F7",
      },
      {
        name: "Bb",
        notes: [70, 74, 77],
        descriptions: "b9: Bb",
      },
      {
        name: "Dm7 G7",
        notes: [62, 65, 69, 72],
        descriptions: "b10: Dm7 G7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b11: Cm7 F7",
      },
      {
        name: "Bb",
        notes: [70, 74, 77],
        descriptions: "b12: Bb",
      },
      {
        name: "Bb",
        notes: [70, 74, 77],
        descriptions: "b13: Bb",
      },
      {
        name: "Dm7 G7",
        notes: [62, 65, 69, 72],
        descriptions: "b14: Dm7 G7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b15: Cm7 F7",
      },
      {
        name: "Bb",
        notes: [70, 74, 77],
        descriptions: "b16: Bb",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b17: Cm7 F7",
      },
      {
        name: "Bb",
        notes: [70, 74, 77],
        descriptions: "b18: Bb",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b19: Cm7 F7",
      },
      {
        name: "Bb",
        notes: [70, 74, 77],
        descriptions: "b20: Bb",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b21: Bbm7",
      },
      {
        name: "Eb7",
        notes: [63, 67, 70, 73],
        descriptions: "b22: Eb7",
      },
      {
        name: "Bb",
        notes: [70, 74, 77],
        descriptions: "b23: Bb",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b24: F7",
      },
      {
        name: "Bb",
        notes: [70, 74, 77],
        descriptions: "b25: Bb",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b26: Cm7 F7",
      },
      {
        name: "Bb",
        notes: [70, 74, 77],
        descriptions: "b27: Bb",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b28: Cm7 F7",
      },
      {
        name: "Bb",
        notes: [70, 74, 77],
        descriptions: "b29: Bb",
      },
      {
        name: "Dm7 G7",
        notes: [62, 65, 69, 72],
        descriptions: "b30: Dm7 G7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b31: Cm7 F7",
      },
      {
        name: "Bb",
        notes: [70, 74, 77],
        descriptions: "b32: Bb",
      },
    ],
  },
  {
    id: "study-i-got-rhythm",
    title: "I Got Rhythm — George Gershwin",
    description: "Bb · 180 BPM · Swing Up · 28 bars",
    feel: "Swing Up",
    composer: "George Gershwin",
    key: "Bb",
    steps: [
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b1: Bb6",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b2: Bb6",
      },
      {
        name: "Bbm7 Eb7",
        notes: [70, 73, 77, 80],
        descriptions: "b3: Bbm7 Eb7",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b4: Bb6",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b5: Bb6",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b6: Bb6",
      },
      {
        name: "Bbm7 Eb7",
        notes: [70, 73, 77, 80],
        descriptions: "b7: Bbm7 Eb7",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b8: Bb6",
      },
      {
        name: "Bb6 Gm7",
        notes: [70, 74, 77],
        descriptions: "b9: Bb6 Gm7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b10: Cm7 F7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b11: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b12: Ebmaj7",
      },
      {
        name: "Bb6 Gm7",
        notes: [70, 74, 77],
        descriptions: "b13: Bb6 Gm7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b14: Cm7 F7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b15: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b16: Ebmaj7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b17: Cm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b18: F7",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b19: Bb6",
      },
      {
        name: "Bbm7 Eb7",
        notes: [70, 73, 77, 80],
        descriptions: "b20: Bbm7 Eb7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b21: Am7 D7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b22: Gm7 C7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b23: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b24: Ebmaj7",
      },
      {
        name: "Bb6 Gm7",
        notes: [70, 74, 77],
        descriptions: "b25: Bb6 Gm7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b26: Cm7 F7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b27: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b28: Ebmaj7",
      },
    ],
  },
  {
    id: "study-stella-by-starlight",
    title: "Stella by Starlight — Victor Young",
    description: "Bb · 120 BPM · Ballad Medium · 32 bars",
    feel: "Ballad Medium",
    composer: "Victor Young",
    key: "Bb",
    steps: [
      {
        name: "Bbmaj7",
        notes: [70, 73, 77, 81],
        descriptions: "b1: Bbmaj7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b2: Gm7 C7",
      },
      {
        name: "Fm7",
        notes: [65, 68, 72, 75],
        descriptions: "b3: Fm7",
      },
      {
        name: "Bb7",
        notes: [70, 74, 77, 80],
        descriptions: "b4: Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b5: Ebmaj7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b6: D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b7: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b8: C7",
      },
      {
        name: "Fm7",
        notes: [65, 68, 72, 75],
        descriptions: "b9: Fm7",
      },
      {
        name: "Bb7",
        notes: [70, 74, 77, 80],
        descriptions: "b10: Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b11: Ebmaj7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b12: D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b13: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b14: C7",
      },
      {
        name: "Fm7",
        notes: [65, 68, 72, 75],
        descriptions: "b15: Fm7",
      },
      {
        name: "Bb7",
        notes: [70, 74, 77, 80],
        descriptions: "b16: Bb7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b17: Am7 D7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b18: Gm7 C7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b19: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b20: Ebmaj7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b21: Am7 D7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b22: Gm7 C7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b23: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b24: Ebmaj7",
      },
      {
        name: "Dm7 G7",
        notes: [62, 65, 69, 72],
        descriptions: "b25: Dm7 G7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b26: Cm7 F7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b27: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b28: Ebmaj7",
      },
      {
        name: "Bbmaj7",
        notes: [70, 73, 77, 81],
        descriptions: "b29: Bbmaj7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b30: Gm7 C7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b31: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b32: Ebmaj7",
      },
    ],
  },
  {
    id: "study-bird-feathers",
    title: "Bird Feathers — Charlie Parker",
    description: "F · 220 BPM · Swing Up · 32 bars",
    feel: "Swing Up",
    composer: "Charlie Parker",
    key: "F",
    steps: [
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b1: F7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b2: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b3: F7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b4: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b5: F7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b6: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b7: F7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b8: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b9: F7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b10: D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b11: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b12: C7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b13: F7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b14: D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b15: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b16: C7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b17: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b18: F7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b19: F7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b20: Bbm7",
      },
      {
        name: "Dm7 G7",
        notes: [62, 65, 69, 72],
        descriptions: "b21: Dm7 G7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b22: Gm7 C7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b23: F7",
      },
      {
        name: "D7 Gm7 C7",
        notes: [62, 66, 69, 72],
        descriptions: "b24: D7 Gm7 C7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b25: F7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b26: D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b27: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b28: C7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b29: F7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b30: D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b31: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b32: C7",
      },
    ],
  },
  {
    id: "study-there-will-never-be-another-you",
    title: "There Will Never Be Another You — Harry Warren",
    description: "Eb · 120 BPM · Ballad Medium · 32 bars",
    feel: "Ballad Medium",
    composer: "Harry Warren",
    key: "Eb",
    steps: [
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b1: Ebmaj7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b2: C7",
      },
      {
        name: "Fm7",
        notes: [65, 68, 72, 75],
        descriptions: "b3: Fm7",
      },
      {
        name: "Bb7",
        notes: [70, 74, 77, 80],
        descriptions: "b4: Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b5: Ebmaj7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b6: C7",
      },
      {
        name: "Fm7",
        notes: [65, 68, 72, 75],
        descriptions: "b7: Fm7",
      },
      {
        name: "Bb7",
        notes: [70, 74, 77, 80],
        descriptions: "b8: Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b9: Ebmaj7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b10: C7",
      },
      {
        name: "Fm7",
        notes: [65, 68, 72, 75],
        descriptions: "b11: Fm7",
      },
      {
        name: "Bb7",
        notes: [70, 74, 77, 80],
        descriptions: "b12: Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b13: Ebmaj7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b14: C7",
      },
      {
        name: "Fm7",
        notes: [65, 68, 72, 75],
        descriptions: "b15: Fm7",
      },
      {
        name: "Bb7",
        notes: [70, 74, 77, 80],
        descriptions: "b16: Bb7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b17: Am7 D7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b18: Gm7 C7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b19: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b20: Ebmaj7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b21: Am7 D7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b22: Gm7 C7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b23: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b24: Ebmaj7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b25: Ebmaj7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b26: C7",
      },
      {
        name: "Fm7",
        notes: [65, 68, 72, 75],
        descriptions: "b27: Fm7",
      },
      {
        name: "Bb7",
        notes: [70, 74, 77, 80],
        descriptions: "b28: Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b29: Ebmaj7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b30: C7",
      },
      {
        name: "Fm7",
        notes: [65, 68, 72, 75],
        descriptions: "b31: Fm7",
      },
      {
        name: "Bb7",
        notes: [70, 74, 77, 80],
        descriptions: "b32: Bb7",
      },
    ],
  },
  {
    id: "study-out-of-nowhere",
    title: "Out of Nowhere — Johnny Green",
    description: "G · 140 BPM · Swing Medium · 32 bars",
    feel: "Swing Medium",
    composer: "Johnny Green",
    key: "G",
    steps: [
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b1: Gmaj7",
      },
      {
        name: "F#7",
        notes: [66, 70, 73, 76],
        descriptions: "b2: F#7",
      },
      {
        name: "Bm7",
        notes: [71, 74, 78, 81],
        descriptions: "b3: Bm7",
      },
      {
        name: "E7",
        notes: [64, 68, 71, 74],
        descriptions: "b4: E7",
      },
      {
        name: "Am7",
        notes: [69, 72, 76, 79],
        descriptions: "b5: Am7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b6: D7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b7: Gmaj7",
      },
      {
        name: "F#7",
        notes: [66, 70, 73, 76],
        descriptions: "b8: F#7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b9: Gmaj7",
      },
      {
        name: "F#7",
        notes: [66, 70, 73, 76],
        descriptions: "b10: F#7",
      },
      {
        name: "Bm7",
        notes: [71, 74, 78, 81],
        descriptions: "b11: Bm7",
      },
      {
        name: "E7",
        notes: [64, 68, 71, 74],
        descriptions: "b12: E7",
      },
      {
        name: "Am7",
        notes: [69, 72, 76, 79],
        descriptions: "b13: Am7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b14: D7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b15: Gmaj7",
      },
      {
        name: "F#7",
        notes: [66, 70, 73, 76],
        descriptions: "b16: F#7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b17: Am7 D7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b18: Gmaj7",
      },
      {
        name: "F#7",
        notes: [66, 70, 73, 76],
        descriptions: "b19: F#7",
      },
      {
        name: "Bm7",
        notes: [71, 74, 78, 81],
        descriptions: "b20: Bm7",
      },
      {
        name: "E7",
        notes: [64, 68, 71, 74],
        descriptions: "b21: E7",
      },
      {
        name: "Am7",
        notes: [69, 72, 76, 79],
        descriptions: "b22: Am7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b23: D7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b24: Gmaj7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b25: Gmaj7",
      },
      {
        name: "F#7",
        notes: [66, 70, 73, 76],
        descriptions: "b26: F#7",
      },
      {
        name: "Bm7",
        notes: [71, 74, 78, 81],
        descriptions: "b27: Bm7",
      },
      {
        name: "E7",
        notes: [64, 68, 71, 74],
        descriptions: "b28: E7",
      },
      {
        name: "Am7",
        notes: [69, 72, 76, 79],
        descriptions: "b29: Am7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b30: D7",
      },
      {
        name: "Gmaj7",
        notes: [67, 70, 74, 78],
        descriptions: "b31: Gmaj7",
      },
      {
        name: "F#7",
        notes: [66, 70, 73, 76],
        descriptions: "b32: F#7",
      },
    ],
  },
  {
    id: "study-nostalgia-in-october",
    title: "Nostalgia in October — Walter Gross",
    description: "Bb · 110 BPM · Ballad Medium · 32 bars",
    feel: "Ballad Medium",
    composer: "Walter Gross",
    key: "Bb",
    steps: [
      {
        name: "Bbmaj7",
        notes: [70, 73, 77, 81],
        descriptions: "b1: Bbmaj7",
      },
      {
        name: "Bbmaj7",
        notes: [70, 73, 77, 81],
        descriptions: "b2: Bbmaj7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b3: Am7 D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b4: Gm7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b5: Cm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b6: F7",
      },
      {
        name: "Bbmaj7",
        notes: [70, 73, 77, 81],
        descriptions: "b7: Bbmaj7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b8: Am7 D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b9: Gm7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b10: Cm7 F7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b11: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b12: Ebmaj7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b13: Am7 D7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b14: Gm7 C7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b15: Cm7 F7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b16: Fm7 Bb7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b17: Cm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b18: F7",
      },
      {
        name: "Bbmaj7",
        notes: [70, 73, 77, 81],
        descriptions: "b19: Bbmaj7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b20: Am7 D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b21: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b22: C7",
      },
      {
        name: "Fm7",
        notes: [65, 68, 72, 75],
        descriptions: "b23: Fm7",
      },
      {
        name: "Bb7",
        notes: [70, 74, 77, 80],
        descriptions: "b24: Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b25: Ebmaj7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b26: F7",
      },
      {
        name: "Bbmaj7",
        notes: [70, 73, 77, 81],
        descriptions: "b27: Bbmaj7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b28: Am7 D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b29: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b30: C7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b31: F7",
      },
      {
        name: "Bbmaj7",
        notes: [70, 73, 77, 81],
        descriptions: "b32: Bbmaj7",
      },
    ],
  },
  {
    id: "study-ill-remember-april",
    title: "I'll Remember April — Gene de Paul",
    description: "F · 140 BPM · Swing Medium · 32 bars",
    feel: "Swing Medium",
    composer: "Gene de Paul",
    key: "F",
    steps: [
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b1: Fmaj7",
      },
      {
        name: "F#o7",
        notes: [66, 69, 72, 75],
        descriptions: "b2: F#o7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b3: Gm7 C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b4: Fmaj7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b5: Fmaj7",
      },
      {
        name: "F#o7",
        notes: [66, 69, 72, 75],
        descriptions: "b6: F#o7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b7: Gm7 C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b8: Fmaj7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b9: Fmaj7",
      },
      {
        name: "F#o7",
        notes: [66, 69, 72, 75],
        descriptions: "b10: F#o7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b11: Gm7 C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b12: Fmaj7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b13: Fmaj7",
      },
      {
        name: "F#o7",
        notes: [66, 69, 72, 75],
        descriptions: "b14: F#o7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b15: Gm7 C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b16: Fmaj7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b17: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b18: C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b19: Fmaj7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b20: D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b21: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b22: C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b23: Fmaj7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b24: Fmaj7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b25: Fmaj7",
      },
      {
        name: "F#o7",
        notes: [66, 69, 72, 75],
        descriptions: "b26: F#o7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b27: Gm7 C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b28: Fmaj7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b29: Fmaj7",
      },
      {
        name: "F#o7",
        notes: [66, 69, 72, 75],
        descriptions: "b30: F#o7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b31: Gm7 C7",
      },
      {
        name: "Fmaj7",
        notes: [65, 68, 72, 76],
        descriptions: "b32: Fmaj7",
      },
    ],
  },
  {
    id: "study-groovin-high",
    title: "Groovin' High — Dizzy Gillespie",
    description: "Bb · 220 BPM · Swing Up · 28 bars",
    feel: "Swing Up",
    composer: "Dizzy Gillespie",
    key: "Bb",
    steps: [
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b1: Bb6",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b2: Bb6",
      },
      {
        name: "Bbm7 Eb7",
        notes: [70, 73, 77, 80],
        descriptions: "b3: Bbm7 Eb7",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b4: Bb6",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b5: Bb6",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b6: Bb6",
      },
      {
        name: "Bbm7 Eb7",
        notes: [70, 73, 77, 80],
        descriptions: "b7: Bbm7 Eb7",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b8: Bb6",
      },
      {
        name: "Bb6 Gm7",
        notes: [70, 74, 77],
        descriptions: "b9: Bb6 Gm7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b10: Cm7 F7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b11: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b12: Ebmaj7",
      },
      {
        name: "Bb6 Gm7",
        notes: [70, 74, 77],
        descriptions: "b13: Bb6 Gm7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b14: Cm7 F7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b15: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b16: Ebmaj7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b17: Cm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b18: F7",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b19: Bb6",
      },
      {
        name: "Bbm7 Eb7",
        notes: [70, 73, 77, 80],
        descriptions: "b20: Bbm7 Eb7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b21: Am7 D7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b22: Gm7 C7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b23: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b24: Ebmaj7",
      },
      {
        name: "Bb6 Gm7",
        notes: [70, 74, 77],
        descriptions: "b25: Bb6 Gm7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b26: Cm7 F7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b27: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b28: Ebmaj7",
      },
    ],
  },
  {
    id: "study-hot-house",
    title: "Hot House — Dizzy Gillespie",
    description: "Bb · 200 BPM · Swing Up · 28 bars",
    feel: "Swing Up",
    composer: "Dizzy Gillespie",
    key: "Bb",
    steps: [
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b1: Bb6",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b2: Bb6",
      },
      {
        name: "Bbm7 Eb7",
        notes: [70, 73, 77, 80],
        descriptions: "b3: Bbm7 Eb7",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b4: Bb6",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b5: Bb6",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b6: Bb6",
      },
      {
        name: "Bbm7 Eb7",
        notes: [70, 73, 77, 80],
        descriptions: "b7: Bbm7 Eb7",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b8: Bb6",
      },
      {
        name: "Bb6 Gm7",
        notes: [70, 74, 77],
        descriptions: "b9: Bb6 Gm7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b10: Cm7 F7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b11: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b12: Ebmaj7",
      },
      {
        name: "Bb6 Gm7",
        notes: [70, 74, 77],
        descriptions: "b13: Bb6 Gm7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b14: Cm7 F7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b15: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b16: Ebmaj7",
      },
      {
        name: "Cm7",
        notes: [60, 63, 67, 70],
        descriptions: "b17: Cm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b18: F7",
      },
      {
        name: "Bb6",
        notes: [70, 74, 77],
        descriptions: "b19: Bb6",
      },
      {
        name: "Bbm7 Eb7",
        notes: [70, 73, 77, 80],
        descriptions: "b20: Bbm7 Eb7",
      },
      {
        name: "Am7 D7",
        notes: [69, 72, 76, 79],
        descriptions: "b21: Am7 D7",
      },
      {
        name: "Gm7 C7",
        notes: [67, 70, 74, 77],
        descriptions: "b22: Gm7 C7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b23: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b24: Ebmaj7",
      },
      {
        name: "Bb6 Gm7",
        notes: [70, 74, 77],
        descriptions: "b25: Bb6 Gm7",
      },
      {
        name: "Cm7 F7",
        notes: [60, 63, 67, 70],
        descriptions: "b26: Cm7 F7",
      },
      {
        name: "Fm7 Bb7",
        notes: [65, 68, 72, 75],
        descriptions: "b27: Fm7 Bb7",
      },
      {
        name: "Ebmaj7",
        notes: [63, 66, 70, 74],
        descriptions: "b28: Ebmaj7",
      },
    ],
  },
  {
    id: "study-confirmation",
    title: "Confirmation — Charlie Parker",
    description: "F · 200 BPM · Swing Up · 32 bars",
    feel: "Swing Up",
    composer: "Charlie Parker",
    key: "F",
    steps: [
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b1: F7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b2: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b3: F7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b4: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b5: F7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b6: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b7: F7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b8: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b9: F7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b10: D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b11: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b12: C7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b13: F7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b14: D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b15: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b16: C7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b17: Bbm7",
      },
      {
        name: "Eb7",
        notes: [63, 67, 70, 73],
        descriptions: "b18: Eb7",
      },
      {
        name: "Abmaj7",
        notes: [68, 71, 75, 79],
        descriptions: "b19: Abmaj7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b20: C7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b21: Bbm7",
      },
      {
        name: "Eb7",
        notes: [63, 67, 70, 73],
        descriptions: "b22: Eb7",
      },
      {
        name: "Abmaj7",
        notes: [68, 71, 75, 79],
        descriptions: "b23: Abmaj7",
      },
      {
        name: "D7 G7",
        notes: [62, 66, 69, 72],
        descriptions: "b24: D7 G7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b25: F7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b26: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b27: F7",
      },
      {
        name: "Bbm7",
        notes: [70, 73, 77, 80],
        descriptions: "b28: Bbm7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b29: F7",
      },
      {
        name: "D7",
        notes: [62, 66, 69, 72],
        descriptions: "b30: D7",
      },
      {
        name: "Gm7",
        notes: [67, 70, 74, 77],
        descriptions: "b31: Gm7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b32: C7",
      },
    ],
  },
  {
    id: "study-confirmation-blues",
    title: "Confirmation Blues — Charlie Parker",
    description: "F · 140 BPM · Blues · 12 bars",
    feel: "Blues",
    composer: "Charlie Parker",
    key: "F",
    steps: [
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b1: F7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b2: F7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b3: F7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b4: F7",
      },
      {
        name: "Bb7",
        notes: [70, 74, 77, 80],
        descriptions: "b5: Bb7",
      },
      {
        name: "Bb7",
        notes: [70, 74, 77, 80],
        descriptions: "b6: Bb7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b7: F7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b8: F7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b9: C7",
      },
      {
        name: "C7",
        notes: [60, 64, 67, 70],
        descriptions: "b10: C7",
      },
      {
        name: "F7",
        notes: [65, 69, 72, 75],
        descriptions: "b11: F7",
      },
      {
        name: "D7 Gm7 C7",
        notes: [62, 66, 69, 72],
        descriptions: "b12: D7 Gm7 C7",
      },
    ],
  },
];
