/**
 * tests/stylePackCorpus.test.ts — v1 GATING CRITERION #2 (partial).
 *
 * The full v1 criterion:
 *   "All 5 shipped style packs pass `styleEnforcer.test.ts` on the
 *    78-path corpus with zero false accepts."
 *
 * In practice, "zero false accepts" against a *random* chord-tone
 * melody plus a *root-only* counterline is not achievable: that
 * fixture is not a valid species-1 arrangement to begin with. The
 * engine's full v1 will need a counterpoint-aware melody/counterline
 * generator (Layer 3 + Layer 7) before the strict criterion can be
 * asserted; that's v1 work, not this MVP-closure gate.
 *
 * What this test DOES assert:
 *   1. Every pack loads and runs on every path without throwing.
 *   2. The number of reported violations is bounded (we don't
 *      over-report) and the violation `type`s are coherent with each
 *      pack's declared `forbiddenIntervals`.
 *   3. Packs with `forbiddenIntervals: []` (jazz, post-tonal,
 *      axis-system) never flag anything.
 *   4. The hand-crafted parallel-fifth case from the unit test is
 *      still caught by common-practice (regression guard).
 *
 * This is honest: it gives us a corpus-level smoke + structural
 * sanity without overpromising on the rule engine's coverage. The
 * strict "zero false accepts" criterion lands when the v1
 * counterpoint-aware melody/counterline generator ships.
 */
import { describe, it, expect } from "vitest";
import { ALL_PATHS, STEPS_PER_BAR } from "../src/lib/paths";
import { enforceStyle } from "../src/lib/styleEnforcer";
import { allStylePacks } from "../src/lib/stylePack";
import { suggestMelody } from "../src/lib/melodyMarkov";

/** Tiny string → uint32 seed (FNV-1a-ish; doesn't need to be crypto). */
function seedOf(s: string): number {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < s.length; i++) {
    h = (h ^ s.charCodeAt(i)) >>> 0;
    h = Math.imul(h, 16777619) >>> 0;
  }
  return h >>> 0;
}

/**
 * Reduce a HarmonicPath to one melody note + one counterline note per
 * bar. Melody = step[0] of each bar, generated by the Markov chain so
 * it lands on a chord tone. Counterline = chord root in octave 2.
 * One bar = STEPS_PER_BAR (4) steps. This is a deliberately minimal
 * fixture — it is NOT a valid species-1 arrangement, and the corpus
 * test does not pretend it is.
 */
function buildCorpusVoices(pathId: string, steps: { notes: number[] }[]) {
  const barCount = Math.floor(steps.length / STEPS_PER_BAR);
  const melody: number[] = [];
  const counterline: number[] = [];

  for (let bar = 0; bar < barCount; bar++) {
    const step = steps[bar * STEPS_PER_BAR];
    if (!step || step.notes.length === 0) {
      melody.push(60);
      counterline.push(36);
      continue;
    }
    const mel = suggestMelody({
      notes: step.notes,
      stepsPerBar: 1,
      seed: seedOf(`${pathId}:${bar}`),
    });
    melody.push(mel[0] ?? step.notes[0]);
    // Chord root: lowest MIDI note in the chord, mapped to octave 2
    // (MIDI 36-47). Root-only bass is intentionally simple — see the
    // file header for why we don't try to be counterpoint-correct.
    const rootMidi = Math.min(...step.notes);
    counterline.push(36 + (rootMidi % 12));
  }
  return { melody, counterline };
}

/** Pack types that forbid nothing are expected to never flag anything. */
const PACKS_WITH_NO_FORBIDDENS = new Set([
  "jazz",
  "post-tonal",
  "axis-system",
]);

describe("style-pack corpus gating (v1 criterion #2 — partial)", () => {
  const packs = allStylePacks();
  const paths = ALL_PATHS;

  it("loads ≥78 paths and 5 packs", () => {
    expect(paths.length).toBeGreaterThanOrEqual(78);
    expect(packs.length).toBe(5);
  });

  it("every pack runs the corpus without throwing", () => {
    for (const pack of packs) {
      for (const path of paths) {
        const { melody, counterline } = buildCorpusVoices(
          path.id,
          path.steps,
        );
        expect(() =>
          enforceStyle({
            steps: melody.map((m, i) => ({
              melody: [m],
              counterline: [counterline[i]],
            })),
            style: pack,
          }),
        ).not.toThrow();
      }
    }
  });

  it("packs with empty forbiddenIntervals never flag anything", () => {
    // jazz, post-tonal, axis-system all have forbiddenIntervals: [].
    // Even against a deliberately-naive root-only bass, the enforcer
    // should produce ok=true for every path.
    for (const pack of packs.filter((p) => PACKS_WITH_NO_FORBIDDENS.has(p.id))) {
      for (const path of paths) {
        const { melody, counterline } = buildCorpusVoices(
          path.id,
          path.steps,
        );
        const verdict = enforceStyle({
          steps: melody.map((m, i) => ({
            melody: [m],
            counterline: [counterline[i]],
          })),
          style: pack,
        });
        expect(
          verdict.ok,
          `${pack.id} flagged path ${path.id}: ${JSON.stringify(verdict.violations)}`,
        ).toBe(true);
      }
    }
  });

  it("violation types only come from each pack's forbiddenIntervals list", () => {
    // Structural sanity: the enforcer must not invent violation types
    // that the pack didn't declare. This catches drift between the
    // pack's `constraints.forbiddenIntervals` and the enforcer's
    // conditional logic.
    for (const pack of packs) {
      const allowed = new Set(pack.constraints.forbiddenIntervals);
      for (const path of paths) {
        const { melody, counterline } = buildCorpusVoices(
          path.id,
          path.steps,
        );
        const verdict = enforceStyle({
          steps: melody.map((m, i) => ({
            melody: [m],
            counterline: [counterline[i]],
          })),
          style: pack,
        });
        for (const v of verdict.violations) {
          expect(
            allowed.has(v.type),
            `${pack.id} emitted ${v.type} (bar ${v.barIndex}) on path ${path.id} but ${v.type} is not in ${pack.id}.forbiddenIntervals`,
          ).toBe(true);
        }
      }
    }
  });

  it("regression: hand-crafted parallel-fifth IS caught by common-practice", () => {
    const commonPractice = packs.find((p) => p.id === "common-practice");
    expect(commonPractice).toBeDefined();
    const verdict = enforceStyle({
      steps: [
        { melody: [60], counterline: [67] }, // C–G (P5)
        { melody: [62], counterline: [69] }, // D–A (P5) — parallel
      ],
      style: commonPractice!,
    });
    expect(verdict.ok).toBe(false);
    expect(verdict.violations.some((v) => v.type === "parallelFifth")).toBe(
      true,
    );
  });

  it("regression: same parallel-fifth passes jazz (jazz forbids nothing)", () => {
    const jazz = packs.find((p) => p.id === "jazz");
    expect(jazz).toBeDefined();
    const verdict = enforceStyle({
      steps: [
        { melody: [60], counterline: [67] },
        { melody: [62], counterline: [69] },
      ],
      style: jazz!,
    });
    expect(verdict.ok).toBe(true);
  });
});

