/**
 * magenta/adapter.ts
 * ──────────────────
 * The "lingua franca" adapter between the app's domain model
 * (HarmonicPath / HarmonicStep) and Magenta's INoteSequence.
 *
 * Why this is the most important file in the magenta/ folder:
 *   every Magenta model — MusicRNN, MusicVAE, GrooVAE, the future
 *   Onsets & Frames transcription — speaks `INoteSequence`. Once
 *   paths round-trip cleanly through here, every one of those
 *   features becomes a one-call integration.
 *
 * The existing app's path shape is *flatter* than the plan assumed:
 *
 *     interface HarmonicPath { steps: HarmonicStep[] }
 *     interface HarmonicStep { name: string; notes: number[] }
 *
 * No bars. No voicings object. No chordSymbol. So we don't try
 * to manufacture one — we treat each `step` as one chord (the
 * natural unit of the catalog) and each `note` inside it as a
 * voice. The adapter is intentionally minimal: a path with N
 * steps × M notes becomes N × M notes at `SPQ×4 / N` spacing,
 * with `step.name` as the chord symbol.
 *
 * If the catalog later gains bars/voicings (the plan hints at this
 * for the voice-leading lab), this is the one file that changes.
 *
 * Quantization helpers live in `./quantize.ts` so this file
 * doesn't pull Magenta's tfjs types into a unit test that
 * doesn't need them.
 */
import type { INoteSequence } from "./INoteSequence";
import type { HarmonicPath, HarmonicStep } from "../lib/paths";

/** Quantization resolution — 4 steps per quarter is Magenta's default. */
export const STEPS_PER_QUARTER = 4;

/** Default tempo when none is supplied. */
export const DEFAULT_QPM = 120;

/** Default velocity for melodic notes; backline gets a smaller value. */
const MELODY_VELOCITY = 96;
const BACKLINE_VELOCITY = 78;

/** Default length of each note when no endTime is given (in seconds). */
const DEFAULT_NOTE_LENGTH_SEC = 0.5;

/**
 * Convert a single HarmonicPath to a quantized NoteSequence suitable
 * for input to `mm.sequences.quantizeNoteSequence`, `MusicRNN.continueSequence`,
 * or the humanizer.
 *
 * The path is treated as one bar of 4/4, with each step at
 * `(4 beats / stepCount)` quarter-notes. This is the natural shape
 * of the catalog (16-step bar grid) and matches what MusicRNN's
 * chord-conditioned configs expect.
 *
 * Returns a *non-quantized* INoteSequence with absolute times —
 * caller can quantize via `mm.sequences.quantizeNoteSequence(ns, STEPS_PER_QUARTER)`
 * before handing to a model that requires it.
 */
export function pathToNoteSequence(
  path: HarmonicPath,
  qpm: number = DEFAULT_QPM,
  opts: { velocity?: number; lengthSec?: number } = {},
): INoteSequence {
  const stepCount = Math.max(1, path.steps.length);
  // seconds per step: each path-step is one (4/stepsPerBar)-note slice of a 4/4 bar
  const secPerStep = (60 / qpm) * (4 / stepCount);
  const lengthSec = opts.lengthSec ?? Math.min(DEFAULT_NOTE_LENGTH_SEC, secPerStep * 1.4);
  const baseVel = opts.velocity ?? MELODY_VELOCITY;

  const notes: NonNullable<INoteSequence["notes"]> = [];
  path.steps.forEach((step: HarmonicStep, si: number) => {
    const start = si * secPerStep;
    if (!Array.isArray(step.notes)) return;
    step.notes.forEach((pitch: number, vi: number) => {
      notes.push({
        pitch,
        startTime: start,
        endTime: start + lengthSec,
        // Melody (vi=0) gets the louder base; voicing voices softer
        velocity: vi === 0 ? baseVel : Math.max(40, baseVel - 12),
        instrument: 0,
      });
    });
  });

  return {
    notes,
    totalTime: stepCount * secPerStep,
    timeSignatures: [{ time: 0, numerator: 4, denominator: 4 }],
    tempos: [{ time: 0, qpm }],
  };
}

/**
 * Extract a chord-symbol array from a path — the form MusicRNN's
 * chord-conditioned models want. We use `step.name` verbatim
 * (e.g. "Dm7", "G7", "Cmaj7", "Bm7b5"); Magenta's `tonal` parses
 * the standard subset of these. Anything it can't parse gets a
 * best-effort `"C"` fallback at the model layer.
 */
export function chordSymbolsOf(path: HarmonicPath): string[] {
  return path.steps.map((s) => s.name || "C");
}

/**
 * Convert a (possibly generated) NoteSequence back into a
 * HarmonicPath. Useful when the humanizer's output (or a
 * MusicRNN continuation) needs to land back in the path catalog
 * for the existing UI to display.
 *
 * Notes are grouped by `Math.floor(startTime / secPerStep)` into
 * the same step grid the adapter used going in.
 *
 * If `qpm` is omitted we read it from the sequence's tempo event;
 * if the sequence has no tempo, we fall back to DEFAULT_QPM.
 */
export function noteSequenceToPath(
  ns: INoteSequence,
  name: string = "Generated",
  description: string = "Generated by the magenta pipeline.",
  stepCount: number = 16,
): HarmonicPath {
  const qpm = ns.tempos?.[0]?.qpm ?? DEFAULT_QPM;
  const secPerStep = (60 / qpm) * (4 / stepCount);

  // Group notes by step bucket
  const buckets: number[][] = Array.from({ length: stepCount }, () => []);
  for (const note of ns.notes ?? []) {
    const idx = Math.min(stepCount - 1, Math.max(0, Math.floor((note.startTime ?? 0) / secPerStep)));
    if (typeof note.pitch === "number") buckets[idx].push(note.pitch);
  }

  // Trim trailing empty buckets so empty paths don't render huge
  while (buckets.length > 1 && buckets[buckets.length - 1].length === 0) buckets.pop();

  const steps: HarmonicStep[] = buckets.map((pitches, i) => {
    const sorted = Array.from(new Set(pitches)).sort((a, b) => a - b);
    return {
      name: `Gen ${i + 1}`,
      notes: sorted,
      descriptions: description,
    };
  });

  return {
    id: `magenta-${Date.now().toString(36)}`,
    title: name,
    description,
    steps,
  };
}

/**
 * Re-export quantization helpers for backward compatibility
 * (the original adapter exported them). Implementation lives in
 * ./quantize.ts so this module stays Magenta-free at import time.
 */
export { quantize, unquantize } from "./quantize";